package com.tamic.statInterface.statsdk .db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig paNoteDaoConfig ;
    private final DaoConfig customerDaoConfig;

    private final TcNoteDao paNoteDao ;
    private final CustomerDao customerDao;


    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);
        paNoteDaoConfig = daoConfigMap.get(TcNoteDao.class).clone();
        paNoteDaoConfig.initIdentityScope(type);


        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);


        paNoteDao = new TcNoteDao(paNoteDaoConfig,this);
        customerDao = new CustomerDao(customerDaoConfig, this);

        registerDao(TcNote.class,paNoteDao);
        registerDao(Customer.class, customerDao);
    }
    
    public void clear() {
        paNoteDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
    }



    public TcNoteDao getPaNoteDao(){
        return paNoteDao ;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

}
