package com.tamic.statInterface.statsdk.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PA_NOTE".
 */
public class TcNote {

    private Long id;
    /** Not-null value. */
    private String firstcloumn;
    /** Not-null value. */
    private String secondcloumn;
    /** Not-null value. */
    private String thirdcloumn;

    public TcNote() {
    }

    public TcNote(Long id) {
        this.id = id;
    }

    public TcNote(Long id, String firstcloumn, String secondcloumn, String thirdcloumn) {
        this.id = id;
        this.firstcloumn = firstcloumn;
        this.secondcloumn = secondcloumn;
        this.thirdcloumn = thirdcloumn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirstcloumn() {
        return firstcloumn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstcloumn(String firstcloumn) {
        this.firstcloumn = firstcloumn;
    }

    /** Not-null value. */
    public String getSecondcloumn() {
        return secondcloumn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSecondcloumn(String secondcloumn) {
        this.secondcloumn = secondcloumn;
    }

    /** Not-null value. */
    public String getThirdcloumn() {
        return thirdcloumn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setThirdcloumn(String thirdcloumn) {
        this.thirdcloumn = thirdcloumn;
    }

}
