package com.tamic.statinterface.stats.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "CUSTOMER".
 */
@Entity
public class Customer {
    @Id
    private Long id;
    /**
     * Not-null value.
     */
    private String name;
    @Generated(hash = 855149052)
    public Customer(Long id, String name) {
        this.id = id;
        this.name = name;
    }
    @Generated(hash = 60841032)
    public Customer() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }




}
