package com.tamic.statinterface.stats.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tamic.statinterface.stats.bean.db.DeviceUser;
import com.tamic.statinterface.stats.bean.db.TcNote;

import com.tamic.statinterface.stats.db.DeviceUserDao;
import com.tamic.statinterface.stats.db.TcNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceUserDaoConfig;
    private final DaoConfig tcNoteDaoConfig;

    private final DeviceUserDao deviceUserDao;
    private final TcNoteDao tcNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceUserDaoConfig = daoConfigMap.get(DeviceUserDao.class).clone();
        deviceUserDaoConfig.initIdentityScope(type);

        tcNoteDaoConfig = daoConfigMap.get(TcNoteDao.class).clone();
        tcNoteDaoConfig.initIdentityScope(type);

        deviceUserDao = new DeviceUserDao(deviceUserDaoConfig, this);
        tcNoteDao = new TcNoteDao(tcNoteDaoConfig, this);

        registerDao(DeviceUser.class, deviceUserDao);
        registerDao(TcNote.class, tcNoteDao);
    }
    
    public void clear() {
        deviceUserDaoConfig.clearIdentityScope();
        tcNoteDaoConfig.clearIdentityScope();
    }

    public DeviceUserDao getDeviceUserDao() {
        return deviceUserDao;
    }

    public TcNoteDao getTcNoteDao() {
        return tcNoteDao;
    }

}
