package com.tamic.statinterface.stats.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tamic.statinterface.stats.bean.TcNote;
import com.tamic.statinterface.stats.bean.DeviceUser;

import com.tamic.statinterface.stats.db.TcNoteDao;
import com.tamic.statinterface.stats.db.DeviceUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tcNoteDaoConfig;
    private final DaoConfig deviceUserDaoConfig;

    private final TcNoteDao tcNoteDao;
    private final DeviceUserDao deviceUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tcNoteDaoConfig = daoConfigMap.get(TcNoteDao.class).clone();
        tcNoteDaoConfig.initIdentityScope(type);

        deviceUserDaoConfig = daoConfigMap.get(DeviceUserDao.class).clone();
        deviceUserDaoConfig.initIdentityScope(type);

        tcNoteDao = new TcNoteDao(tcNoteDaoConfig, this);
        deviceUserDao = new DeviceUserDao(deviceUserDaoConfig, this);

        registerDao(TcNote.class, tcNoteDao);
        registerDao(DeviceUser.class, deviceUserDao);
    }
    
    public void clear() {
        tcNoteDaoConfig.clearIdentityScope();
        deviceUserDaoConfig.clearIdentityScope();
    }

    public TcNoteDao getTcNoteDao() {
        return tcNoteDao;
    }

    public DeviceUserDao getDeviceUserDao() {
        return deviceUserDao;
    }

}
