package com.tamic.statinterface.stats.bean.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Keep;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "PA_NOTE".
 */
@Entity
public class TcNote {

    @Id
    private Long id;
    /**
     * Not-null value.
     */
    private String firstCloumn;
    /**
     * Not-null value.
     */
    private String secondCloumn;
    /**
     * Not-null value.
     */
    private String thirdCloumn;

    private String fourCloumn;

    private Integer status;

    public static final int DATA_STATUS_SAVED = 0;
    public static final int DATA_STATUS_SENDING = 1;

    public TcNote() {
    }
    @Keep
    public TcNote(Long id) {
        this.id = id;
    }
    @Generated(hash = 2088856789)
    public TcNote(Long id, String firstCloumn, String secondCloumn, String thirdCloumn,
            String fourCloumn, Integer status) {
        this.id = id;
        this.firstCloumn = firstCloumn;
        this.secondCloumn = secondCloumn;
        this.thirdCloumn = thirdCloumn;
        this.fourCloumn = fourCloumn;
        this.status = status;
    }



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstCloumn() {
        return firstCloumn;
    }

    public void setFirstCloumn(String firstCloumn) {
        this.firstCloumn = firstCloumn;
    }

    public String getSecondCloumn() {
        return secondCloumn;
    }

    public void setSecondCloumn(String secondCloumn) {
        this.secondCloumn = secondCloumn;
    }

    public String getThirdCloumn() {
        return thirdCloumn;
    }

    public void setThirdCloumn(String thirdCloumn) {
        this.thirdCloumn = thirdCloumn;
    }

    public String getFourCloumn() {
        return fourCloumn;
    }

    public void setFourCloumn(String fourCloumn) {
        this.fourCloumn = fourCloumn;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}
